// Definición de datos de prueba.
const fakeElements = [
  {
    icono: "sandwich",
    id: "sandwich001",
    nombre: "churrasco chacarero",
    categoria: "sandwich",
    valor: "$6.900",
    disponibilidad: true,
    unidades: 30,
  },
  {
    icono: "sandwich",
    id: "sandwich002",
    nombre: "churrasco italiano",
    categoria: "sandwich",
    valor: "$6.900",
    disponibilidad: true,
    unidades: 30,
  },
  {
    icono: "sandwich",
    id: "sandwich003",
    nombre: "churrasco completo",
    categoria: "sandwich",
    valor: "$6.900",
    disponibilidad: true,
    unidades: 30,
  },
  {
    icono: "sandwich",
    id: "sandwich004",
    nombre: "churrasco luco",
    categoria: "sandwich",
    valor: "$6.900",
    disponibilidad: true,
    unidades: 30,
  },
  {
    icono: "sandwich",
    id: "sandwich005",
    nombre: "churrasco dinamico",
    categoria: "sandwich",
    valor: "$6.900",
    disponibilidad: true,
    unidades: 30,
  },
  {
    icono: "sandwich",
    id: "sandwich006",
    nombre: "churrasco americano",
    categoria: "sandwich",
    valor: "$6.900",
    disponibilidad: true,
    unidades: 30,
  },
  {
    icono: "sandwich",
    id: "sandwich002",
    nombre: "churrasco italiano",
    categoria: "sandwich",
    valor: "$6.900",
    disponibilidad: true,
    unidades: 30,
  },
  {
    icono: "sandwich",
    id: "sandwich003",
    nombre: "churrasco completo",
    categoria: "sandwich",
    valor: "$6.900",
    disponibilidad: true,
    unidades: 30,
  },
  {
    icono: "sandwich",
    id: "sandwich004",
    nombre: "churrasco luco",
    categoria: "sandwich",
    valor: "$6.900",
    disponibilidad: true,
    unidades: 30,
  },
  {
    icono: "sandwich",
    id: "sandwich005",
    nombre: "churrasco dinamico",
    categoria: "sandwich",
    valor: "$6.900",
    disponibilidad: true,
    unidades: 30,
  },
  {
    icono: "sandwich",
    id: "sandwich006",
    nombre: "churrasco americano",
    categoria: "sandwich",
    valor: "$6.900",
    disponibilidad: true,
    unidades: 30,
  },
];

// Exportación
export default fakeElements;
